### ISSUE TITLE
Seems broken on the latest version of discord

### ISSUE THREAD

**Issue by ajayyy** [EnKrypt/DiscordEncryption#3]
Don't worry about fixing it, it's not an urgent need. I just thought this was such a cool idea, nice job!

**Comment by EnKrypt** [comment]
Should be fixed now, feel free to update the plugin with the new file.

The discord devs removed a random class for some reason which broke the plugin. If they keep going at this rate, some day fixing this plugin won't be as easy as it was today.

Cheers.

**Comment by ajayyy** [comment]
Thanks!
